ExpenseManager/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;
using X.PagedList;
using ExpenseManager.ViewModels;

namespace ExpenseManager.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly Context _context;

        public ExpensesController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? page)
        {
            const int pageItems = 10;
            int pageNumber = (page ?? 1);

            ViewData["Months"] = new SelectList(_context.Months.Where(x => x.MonthId == x.Salary.MonthId), "MonthId", "Name");

            var context = _context.Expenses.Include(e => e.ExpenseType).Include(e => e.Month).OrderBy(e => e.MonthId);
            return View(await context.ToPagedListAsync(pageNumber, pageItems));
        }

        public IActionResult Create()
        {
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name");
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpenseId,MonthId,ExpenseTypeId,Value")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmation"] = "Expense Registered Successfully.";

                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses.FindAsync(id);
            if (expense == null)
            {
                return NotFound();
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExpenseId,MonthId,ExpenseTypeId,Value")] Expense expense)
        {
            if (id != expense.ExpenseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirmation"] = "Expense Updated Successfully.";
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(expense.ExpenseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var expense = await _context.Expenses.FindAsync(id);
            _context.Expenses.Remove(expense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseExists(int id)
        {
            return _context.Expenses.Any(e => e.ExpenseId == id);
        }

        public JsonResult TotalSpendingMonths(int monthId)
        {
            TotalExpendituresMonthViewModel spending = new TotalExpendituresMonthViewModel();

            spending.TotalAmountExpenditure = _context.Expenses.Where(d => d.Month.MonthId == monthId).Sum(d => d.Value);
            spending.Salary = _context.Salaries.Where(s => s.Month.MonthId == monthId).Select(s => s.Value).FirstOrDefault();

            return Json(spending);
        }

        public JsonResult MonthExpense(int monthId)
        {
            var query = from expenses in _context.Expenses
                        where expenses.Month.MonthId == monthId
                        group expenses by expenses.ExpenseType.Name into g
                        select new
                        {
                            ExpenseType = g.Key,
                            Value = g.Sum(d => d.Value)
                        };

            return Json(query);
        }

        public JsonResult TotalExpenses()
        {
            var query = _context.Expenses
                .OrderBy(m => m.Month.MonthId)
                .GroupBy(m => m.Month.MonthId)
                .Select(d => new { NameMonths = d.Select(x => x.Month.Name).Distinct(), Value = d.Sum(x => x.Value) });

            return Json(query);
        }
    }
}

ExpenseManager/ViewComponents/StatisticsViewComponent.cs
using ExpenseManager.Models;
using ExpenseManager.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.ViewComponents
{
    public class StatisticsViewComponent : ViewComponent
    {
        private readonly Context _context;

        public StatisticsViewComponent(Context context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            StatisticsViewModel statistics = new StatisticsViewModel();

            statistics.LowerExpense = _context.Expenses.Min(x => x.Value);
            statistics.GreatestExpense = _context.Expenses.Max(x => x.Value);
            statistics.QuantityExpenses = _context.Expenses.Count();

            return View(statistics);
        }
    }
}

ExpenseManager/Views/Expenses/Create.cshtml
@model ExpenseManager.Models.Expense

@{
    ViewData["Title"] = "New Expense";
}


<div class="formCreate">
    <h6>New Expense</h6>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" class="form rounded border">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="MonthId" class="control-label">Month</label>
                    <select asp-for="MonthId" class="form-control" asp-items="ViewBag.MonthId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="ExpenseTypeId" class="control-label">Expense Type</label>
                    <div class="input-group">
                        <select asp-for="ExpenseTypeId" class="form-control" asp-items="ViewBag.ExpenseTypeId"></select>
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-info" data-toggle="tooltip" data-placement="right" title="Add New Expense Type" onclick="ShowModal()">
                                <i class="far fa-plus-square"></i>
                            </button>
                        </div>
                    </div>

                </div>
                <div class="form-group">
                    <label asp-for="Value" class="control-label"></label>
                    <input asp-for="Value" class="form-control" />
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-outline-success btn-sm" /> &nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add New Expense</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input class="form-control txtExpense" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnAdd">Add</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        function ShowModal() {
            $(".modal").modal();
            $(".btnAdd").on('click', function () {
                var txtExpense = $(".txtExpense").val();
                $.ajax({
                    url: "/ExpenseTypes/AddExpenseType",
                    method: "POST",
                    data: { txtExpense: txtExpense },
                    success: function (data) {
                        if (!data) {
                            $(".modal").modal('hide');
                            $(".modal").modal('dispose');
                            $(".btnAdd").unbind('click');
                            $(".txtExpense").val('');
                            alert("Type of expense already registered.");
                        }
                        else location.reload(true);
                    }
                })
            });
        }
    </script>
}

ExpenseManager/Views/Expenses/Edit.cshtml
@model ExpenseManager.Models.Expense

@{
    ViewData["Title"] = "Update Expense";
}

<div class="formCreate">
    <h6>Update Expense</h6>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" class="form rounded border">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ExpenseId" />
                <div class="form-group">
                    <label asp-for="MonthId" class="control-label">Month</label>
                    <select asp-for="MonthId" class="form-control" asp-items="ViewBag.MonthId"></select>
                    <span asp-validation-for="MonthId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExpenseTypeId" class="control-label">Expense Type</label>
                    <select asp-for="ExpenseTypeId" class="form-control" asp-items="ViewBag.ExpenseTypeId"></select>
                    <span asp-validation-for="ExpenseTypeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value" class="control-label"></label>
                    <input asp-for="Value" class="form-control" />
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-outline-success btn-sm" /> &nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseManager/Views/Expenses/Index.cshtml
@model X.PagedList.IPagedList<ExpenseManager.Models.Expense>
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Common

@{
    ViewData["Title"] = "Registered Expenses";
}
<br />
<div class="table">
    <div class="container">
        <p class="btnNew">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm">New Expense</a>
        </p>

        @if (TempData["Confirmation"] != null)
        {
            <h6 class="alert alert-success">@TempData["Confirmation"]</h6>
        }


        <div class="row justify-content-md-center">
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"><strong>Month</strong></label>
                <div class="col-sm-9">
                    <select class="form-control chooseMonth" asp-items="ViewBag.Months"></select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <partial name="_TotalSpendingMonth" />
            </div>

            <div class="col">
                <partial name="_ExpenseMonth" />
            </div>
        </div>

        <div class="row">
            <partial name="_TotalExpenses" />
        </div>

        <div class="statistics">
            <div class="alert alert-primary">
                @await Component.InvokeAsync("Statistics")
            </div>
        </div>

        <div class="mainTable">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            Months
                        </th>
                        <th>
                            Expense Type
                        </th>
                        <th>
                            Value
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Month.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ExpenseType.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Value)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ExpenseId" class="btn btn-outline-info btn-sm">Update</a> |
                                <a onclick="ShowModal(@item.ExpenseId)" class="btn btn-outline-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", "Expenses", new { page }), new PagedListRenderOptionsBase
{
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" }
})

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you want to proceed with the exclusion of this expense ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnDelete">Yes</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/bundle.min.js"></script>
    <script>
        LoadSpendingDataMonths();
        LoadDataTotalExpenditureMonths();
        LoadDataTotalExpenses();

        function ShowModal(id) {
            $(".modal").modal();
            $(".btnDelete").on('click', function () {
                $.ajax({
                    url: "Expenses/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>

}