ExpenseManager/Controllers/ExpenseTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;

namespace ExpenseManager.Controllers
{
    public class ExpenseTypesController : Controller
    {
        private readonly Context _context;

        public ExpenseTypesController(Context context)
        {
            _context = context;
        }

        // GET: ExpenseTypes
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.ExpenseTypes.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string txtSearch)
        {
            if (!String.IsNullOrEmpty(txtSearch))
                return View(await _context.ExpenseTypes.Where(td => td.Name.ToUpper().Contains(txtSearch.ToUpper())).ToListAsync());

            return View(await _context.ExpenseTypes.ToListAsync());
        }

        public async Task<JsonResult> ExpenseTypeExist(string name)
        {
            if (await _context.ExpenseTypes.AnyAsync(td => td.Name.ToUpper() == name.ToUpper()))
                return Json("This Type of Expense Already Exists");

            return Json(true);
        }

        public JsonResult AddExpenseType(string txtExpense)
        {
            if (!String.IsNullOrEmpty(txtExpense))
            {
                if (!_context.ExpenseTypes.Any(td => td.Name.ToUpper() == txtExpense.ToUpper()))
                {
                    ExpenseType expenseType = new ExpenseType();
                    expenseType.Name = txtExpense;
                    _context.Add(expenseType);
                    _context.SaveChanges();

                    return Json(true);
                }
            }

            return Json(false);
        }

        // GET: ExpenseTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpenseTypeId,Name")] ExpenseType expenseType)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmation"] = expenseType.Name + " Was Successfully Registered. ";
                _context.Add(expenseType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expenseType);
        }

        // GET: ExpenseTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseType = await _context.ExpenseTypes.FindAsync(id);
            if (expenseType == null)
            {
                return NotFound();
            }
            return View(expenseType);
        }

        // POST: ExpenseTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExpenseTypeId,Name")] ExpenseType expenseType)
        {
            if (id != expenseType.ExpenseTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirmation"] = expenseType.Name + " Was Successfully Updated. ";
                    _context.Update(expenseType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseTypeExists(expenseType.ExpenseTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expenseType);
        }

        // POST: ExpenseTypes/Delete/5
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var expenseType = await _context.ExpenseTypes.FindAsync(id);
            TempData["Confirmation"] = expenseType.Name + " Was Successfully Deleted. ";
            _context.ExpenseTypes.Remove(expenseType);
            await _context.SaveChangesAsync();
            return Json(expenseType.Name + " deleted successfully.");
        }

        private bool ExpenseTypeExists(int id)
        {
            return _context.ExpenseTypes.Any(e => e.ExpenseTypeId == id);
        }
    }
}

ExpenseManager/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;
using X.PagedList;
using ExpenseManager.ViewModels;

namespace ExpenseManager.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly Context _context;

        public ExpensesController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? page)
        {
            const int pageItems = 10;
            int pageNumber = (page ?? 1);

            ViewData["Months"] = new SelectList(_context.Months.Where(x => x.MonthId == x.Salary.MonthId), "MonthId", "Name");

            var context = _context.Expenses.Include(e => e.ExpenseType).Include(e => e.Month).OrderBy(e => e.MonthId);
            return View(await context.ToPagedListAsync(pageNumber, pageItems));
        }

        public IActionResult Create()
        {
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name");
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExpenseId,MonthId,ExpenseTypeId,Value")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmation"] = "Expense Registered Successfully.";

                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses.FindAsync(id);
            if (expense == null)
            {
                return NotFound();
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExpenseId,MonthId,ExpenseTypeId,Value")] Expense expense)
        {
            if (id != expense.ExpenseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirmation"] = "Expense Updated Successfully.";
                    _context.Update(expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(expense.ExpenseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months, "MonthId", "Name", expense.MonthId);
            ViewData["ExpenseTypeId"] = new SelectList(_context.ExpenseTypes, "ExpenseTypeId", "Name", expense.ExpenseTypeId);
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var expense = await _context.Expenses.FindAsync(id);
            _context.Expenses.Remove(expense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseExists(int id)
        {
            return _context.Expenses.Any(e => e.ExpenseId == id);
        }

        public JsonResult TotalSpendingMonths(int monthId)
        {
            TotalExpendituresMonthViewModel spending = new TotalExpendituresMonthViewModel();

            spending.TotalAmountExpenditure = _context.Expenses.Where(d => d.Month.MonthId == monthId).Sum(d => d.Value);
            spending.Salary = _context.Salaries.Where(s => s.Month.MonthId == monthId).Select(s => s.Value).FirstOrDefault();

            return Json(spending);
        }

        public JsonResult MonthExpense(int monthId)
        {
            var query = from expenses in _context.Expenses
                        where expenses.Month.MonthId == monthId
                        group expenses by expenses.ExpenseType.Name into g
                        select new
                        {
                            ExpenseType = g.Key,
                            Value = g.Sum(d => d.Value)
                        };

            return Json(query);
        }

        public JsonResult TotalExpenses()
        {
            var query = _context.Expenses
                .OrderBy(m => m.Month.MonthId)
                .GroupBy(m => m.Month.MonthId)
                .Select(d => new { NameMonths = d.Select(x => x.Month.Name).Distinct(), Value = d.Sum(x => x.Value) });

            return Json(query);
        }
    }
}

ExpenseManager/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;

namespace ExpenseManager.Controllers
{
    public class SalariesController : Controller
    {
        private readonly Context _context;

        public SalariesController(Context context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var context = _context.Salaries.Include(s => s.Month);
            return View(await context.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string txtSearch)
        {
            if (!String.IsNullOrEmpty(txtSearch))
            {
                return View(await _context.Salaries.Include(s => s.Month).Where(m => m.Month.Name.ToUpper().Contains(txtSearch.ToUpper())).ToListAsync());
            }

            return View(await _context.Salaries.Include(s => s.Month).ToListAsync());
        }

        // GET: Salaries/Create
        public IActionResult Create()
        {
            ViewData["MonthId"] = new SelectList(_context.Months.Where(x => x.MonthId != x.Salary.MonthId), "MonthId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalaryId,MonthId,Value")] Salary salary)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirmation"]= "Salary Successfully Registered.";
                _context.Add(salary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId != s.Salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

        // GET: Salaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries.FindAsync(id);
            if (salary == null)
            {
                return NotFound();
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId == s.Salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

        // POST: Salaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalaryId,MonthId,Value")] Salary salary)
        {
            if (id != salary.SalaryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salary);
                    await _context.SaveChangesAsync();
                    TempData["Confirmation"] = "Salary Successfully Updated.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryExists(salary.SalaryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId == s.Salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var salary = await _context.Salaries.FindAsync(id);
            _context.Salaries.Remove(salary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryExists(int id)
        {
            return _context.Salaries.Any(e => e.SalaryId == id);
        }
    }
}

ExpenseManager/Views/Shared/_ExpenseMonth.cshtml
<div class="ChartExpensesMonths">
    <canvas id="ChartExpensesMonths" style="height:400px;width:400px;"></canvas>
</div>

ExpenseManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManager</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" />
        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Expenses">ExpensesManager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Expenses">Expenses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Salaries">Salaries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="ExpenseTypes">Expense Types</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - ExpenseManager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ExpenseManager/Views/Shared/_TotalExpenses.cshtml
<canvas id="ChartTotalExpenses"></canvas>

ExpenseManager/Views/Shared/_TotalSpendingMonth.cshtml
<div class="ChartCostTotalMonths">
    <canvas id="ChartCostTotalMonths" style="width: 400px; height: 400px"></canvas>
</div>